def run(target)
  puts(system("./vim-themis/bin/themis", target) ? "OK" : "NG")
end

guard :shell do
  watch /^.+\.vim$/ do |m|
    puts "start #{m[0]}"
    run "./test/"
  end

  watch /^.+\.vimspec$/ do |m|
    puts "start #{m[0]}"
    run m[0]
  end
end
